### Hello World
GET http://localhost:3000

### Users
GET http://localhost:3000/users

### Contact by ID
GET http://localhost:3000/users/66f1f2b0229f3bff56b01707

### Hello World
GET https://project1-x6rx.onrender.com

### Users
GET https://project1-x6rx.onrender.com/users

### Contact by ID from Render
GET https://project1-x6rx.onrender.com/users/66f1f1fc229f3bff56b01706

### Update user
PUT https://project1-x6rx.onrender.com/users/66f1f1fc229f3bff56b01706
Content-Type: application/application/json

{
    "firstName": "John",
    "lastName": "Smith",
    "email": "john.smith82@gmail.com",
    "favoriteColor": "green",
    "birthday": "6/23/72"
}

### Create Contact
POST https://project1-x6rx.onrender.com/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "jane.doe55@gmail.com",
    "favoriteColor": "blue",
    "birthday": "3/28/89"
}

### Delete Contact
DELETE http://localhost:3000/users/66f8ba74c2461c3a75a676a9 HTTP/1.1
